name = "FEATS"
version = "0.1.0"
license = "BSD"
author = ["Damian Rouson"]
maintainer = "damian@sourceryinstitute.org"
copyright = "2021 Sourcery Institute"

[dependencies]
assert = {git = "https://github.com/sourceryinstitute/assert", tag = "1.3.0"}
dag = {git = "https://github.com/sourceryinstitute/dag", tag = "2.1.1"}

[dev-dependencies]
vegetables = {git = "https://gitlab.com/everythingfunctional/vegetables", tag = "v7.0.2"}

[[test]]
name="unit"
source-dir="tests"
main="main.f90"

[[example]]
name="build_feats"
source-dir="example/build_feats"
main="main.f90"

[[example]]
name="quadratic_solver"
source-dir="example/quadratic_solver"
main="main.f90"
