name = "FEATS"
version = "21.02.04"
license = "BSD"
author = ["Damian Rouson"]
maintainer = "damian@sourceryinstitute.org"
copyright = "2021 Sourcery Institute"

[dependencies]
assert = {git = "https://github.com/sourceryinstitute/assert", tag = "1.0.0"}
sourcery = {git = "https://github.com/sourceryinstitute/sourcery", tag = "21.08.31"}
dag = {git = "https://github.com/sourceryinstitute/dag", tag = "2021.08.31"}

[dev-dependencies]
vegetables = {git = "https://gitlab.com/everythingfunctional/vegetables", tag = "v7.0.2"}

[[test]]
name="unit"
source-dir="tests"
main="main.f90"

[[example]]
name="build-feats"
source-dir="example/build-feats"
main="build-feats.f90"
