name = "FEATS"
version = "0.1.0"
license = "BSD"
author = ["Damian Rouson"]
maintainer = "damian@sourceryinstitute.org"
copyright = "2021 Sourcery Institute"

[dependencies]
dag = {git = "https://github.com/sourceryinstitute/dag", rev="e3f8ec61635842cc1e28d09bff34391c328fd75e" } #, tag = "3.0.0"}

[[example]]
name="build_feats"
source-dir="example/build_feats"
main="main.f90"

[[example]]
name="quadratic_solver"
source-dir="example/quadratic_solver"
main="main.f90"

[[example]]
name="lu_decomp"
source-dir="example/lu_decomp"
main="main.f90"
