name = "sourcery"
version = "1.0.0"
license = "BSD"
author = ["Damian Rouson"]
maintainer = "damian@sourceryinstitute.org"
copyright = "2020 Sourcery Institute"

[dependencies]
dag = {git = "https://github.com/sourceryinstitute/sourcery", commit = "b5331415ec7fb9f78ee5acc7e0396d2ac15b68ff"}

[dev-dependencies]
vegetables = {git = "https://gitlab.com/everythingfunctional/vegetables", tag = "v7.0.2"}

[[test]]
name="unit"
source-dir="tests"
main="main.f90"
