name = "FEATS"
version = "0.1.0"
license = "BSD"
author = ["Damian Rouson"]
maintainer = "damian@sourceryinstitute.org"
copyright = "2021 Sourcery Institute"

[[example]]
name="quadratic_solver"
source-dir="example/quadratic_solver"
main="main.f90"

[[example]]
name="lu_decomp"
source-dir="example/lu_decomp"
main="main.f90"
