@startuml
Title "Classes in the FEATS Main Program"

hide empty members

class data_location_map_t{
  task_numbers : integer[]
  image_numbers : integer[]
  location_of(task : integer) : integer
}

class payload_t{
  payload : character(len=:), allocatable
}

object mailbox{
  payloads : payload_t[]
}

mailbox *-down- payload_t

abstract class task_t{
  {abstract} execute(input_locations : data_location_map_t, mailbox)
}
class task_item_t{
  {abstract} task : task_t
  execute(input_locations : data_location_map_t, mailbox)
}

task_t -left-> data_location_map_t : accepts
task_t -left-> mailbox : accepts

task_item_t *-down- task_t
task_item_t -left-> data_location_map_t : accepts
task_item_t -left-> mailbox : accepts

class dag_t{
}

class application_t{
  dag : dag_t
  task_item : task_item_t[]
}
note right: inv: self%dag%get_num_edges()==size(self%task_item[])
application_t *-down- dag_t
application_t *-down- task_item_t


class image_t{
  run(application : application_t) : data_location_map_t
}

application_t -left-> image_t : accepts

@enduml
