run – FEATS
run Module Procedure
31 statements
Source File
module procedure run module module function run(self, application) result(results) Interface →
Arguments
Type Intent Optional Attributes Name
class(image_t), intent(in) :: self
type(application_t), intent(in) :: application
Return Value type(task_payload_map_t), allocatable
Calls
Called by
Contents
None
Call graph
run calls do_work, assign_task, run
do_work calls upstream_task_nums, upstream_task_imagenums
assign_task calls assign_completed_to_images